#!/bin/bash
#change this ssid with your device ssid

#function to add new devices to config file
function enlist(){
	if test -f "$2"; then
    	touch $2
	fi
	lc=`wc -l $2 | awk '{print $1}'`
	echo devices$lc=\"$1\" >> $2
	printf "devices$lc=$1 added to $2\n\nCurrent devices are: \n"
	cat $2
	exit
}

function connect(){
	device=$1

	#temporary variable to write logs
	tmpfile=$(mktemp /tmp/btcon.XXXXXX)

	#removes temporary variable on abnormal or normal exit from script
	trap "rm -f $tmpfile" 0 2 3 15


	rfkill unblock bluetooth 

	coproc bluetoothctl 2>&1 1>$tmpfile
	echo -e 'power on' >&${COPROC[1]}
	echo -e 'scan on' >&${COPROC[1]}

	gnome-terminal --wait -- bash -c "tail -f $tmpfile && echo 'Press ctr + c to exit~> ' && exit"

	echo -e "pair ${device}" >&${COPROC[1]}
	echo -e "connect ${device}" >&${COPROC[1]}

	gnome-terminal --wait -- bash -c "tail -f $tmpfile && echo 'Press ctr + c to exit~> ' && exit"
}

function reconnect(){
	rfkill unblock bluetooth 

	cur_device=""

	tmpvar=$(mktemp /tmp/headph-bluetooth.XXXXXX)
	trap "rm -f $tmpvar" 0 2 3 15
	coproc bluetoothctl 2>&1 1>$tmpvar
	echo -e "list" >&${COPROC[1]}
	sleep 2
	# cat $tmpvar
	cur_device=`cat $tmpvar | grep -i '[NEW] Controller ..:..:..:..:..:.. Instantinopaul'| awk '{print $3}'`
	echo "this is $cur_device"
	connect $cur_device
	exit
}

#config file path
FILE='/home/sayan/.btcon/btcon'

while getopts n:r options; do
	case $options in
		n) enlist $OPTARG $FILE;;
		r) reconnect;;
	esac
done

device="FC:58:FA:D8:60:95"
	#get device names from config file
	if test -f "$FILE"; then
	    source $FILE
	fi

	#catches the ssid passed as argument and overrides the default ssid initialized
	if test $# -ne 0
	then 
		device_name=devices$1
		device=${!device_name}
	fi

connect $device

